export const HOME_PAGE = '/Sneakers-Website/';
export const MEN_PAGE = '/Sneakers-Website/men-sneakers';
export const WOMEN_PAGE = '/Sneakers-Website/women-sneakers';
export const ADIDAS_PAGE = '/Sneakers-Website/adidas-sneakers';
export const NIKE_PAGE = '/Sneakers-Website/nike-sneakers';
export const SNEAKERS_PAGE = '/Sneakers-Website/sneakers-page/:id';
export const SIGNIN_PAGE = '/Sneakers-Website/sign-in';
export const CONTACT_US_PAGE = '/Sneakers-Website/contact-us';
export const PAGE_NOT_FOUND = '/Sneakers-Website/*';
export const CART_PAGE = '/Sneakers-Website/cart-sneakers';
export const FAVORITE_PAGE = '/Sneakers-Website/favorite-sneakers';
export const PRIVACY_POLICY = '/Sneakers-Website/privacy-policy';
export const COOKIE_POLICY = '/Sneakers-Website/cookie-policy';
export const RETURN_AND_EXCHANGE_POLICY =
	'/Sneakers-Website/return-and-exchange-policy';
export const DELIVERY_POLICY = '/Sneakers-Website/delivery-policy';
export const TERMS_OF_SALE = '/Sneakers-Website/terms-of-sale';
export const TERMS_OF_USE = '/Sneakers-Website/terms-of-use';
export const BUY_PAGE = '/Sneakers-Website/checkout';
